- name: Установите Nginx, скопируйте HTML-файл и настройте виртуальный путь/сервер
  hosts: webservers
  become: yes  # Запуск задач с повышенными привилегиями (sudo)
  
  vars:
    root_dir: /var/www/ansible #корневая папка проекта ansible
    service_name: "{{ ansible_hostname }}"  # Получаем имя хоста из фактов Ansible
    current_date: "{{ ansible_date_time.date }}"  # Получаем текущую дату из фактов Ansible


  tasks:
    - name: Install Nginx #установка nginx
      apt:
        name: nginx
        state: present  # Убедитесь, что установлен Nginx
   
#    - name: Configure virtual server on port 8080 #Настройка виртуального сервера на порту 8080
#      blockinfile:
#        path: /etc/nginx/sites-enabled/default
#        block: |
#          server {
#              listen 8080;
#              server_name ansible;
#              root {{root_dir}};
#              index index.html;
#          }

    - name: update nginix config #загрузка конфига проекта
      ansible.builtin.template:
        src: cfg/ansible.j2

        dest: /etc/nginx/sites-enabled/ansible


    - name: Create directory {{root_dir}} #создание директории
      file:
        path: "{{root_dir}}"
        state: directory
        mode: '0755'  # Set directory permissions

 #   - name: Copy HTML file
 #     copy:
 #       src: /html/index.html 
 #       dest: {{root_dir}}/index.html  

    - name: update index.html #копирование index.html
      ansible.builtin.copy:
        src: /templates/index.html.j2
        dest: "{{root_dir}}/index.html"


    - name: Check Nginx service status
      systemd:
        name: nginx
        state: started
        enabled: yes    
    

    
  handlers:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

- name: Verify Nginx
  hosts: webservers
  gather_facts: no  
  tasks:
    - name: Check if Nginx is running on port 8080
      wait_for:
        host: "{{ ansible_host }}"
        port: 8080
        state: started
        timeout: 30  # Timeout in seconds
